# serverless.yml

service: lambda-pdf-report-demo

plugins:
  - serverless-python-requirements
  - serverless-apigw-binary

custom:
  pythonRequirements:
    dockerizePip: true

  apigwBinary:
    types:
      - "application/pdf"

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-2
  environment:
    WKHTMLTOPDF_PATH: "/opt/bin/wkhtmltopdf"
  usagePlan:
    throttle:
      burstLimit: 5
      rateLimit: 2

functions:
  app:
    handler: app.lambda_handler
    layers:
      - { Ref: WkhtmltopdfLambdaLayer }
    events:
      - http: ANY /
      - http: "ANY {proxy+}"

layers:
  wkhtmltopdf:
    # run download-wkhtml.sh to put the binary in this folder
    path: var/wkhtmltopdf/
    description: Provides the wkhtmltopdf binary
    compatibleRuntimes:
      - python3.7
