# serverless.yml

service: lambda-pdf-report-demo

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false

  pythonRequirements:
    dockerizePip: true

  localstack:
    host: http://localhost
    stages:
      - local
    autostart: true
    lambda:
      mountCode: false
    debug: true

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-2

functions:
  app:
    handler: wsgi_handler.handler

    events:
      - http: ANY /
      - http: "ANY {proxy+}"
