# serverless.yml

service: lambda-pdf-report-demo

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false

  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-2

functions:
  app:
    handler: wsgi_handler.handler

    events:
      - http:
          path: /
          method: post
